-- ==========================================================================
-- SUPABASE DATABASE SETUP SCRIPT FOR WEBSITE AM PREMIUM
-- Copy & Paste skrip ini di SQL Editor di dashboard Supabase Anda (supabase.com)
-- ==========================================================================

-- 1. Buat tabel activations
CREATE TABLE IF NOT EXISTS public.activations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL,
    code_order TEXT NOT NULL UNIQUE,
    status TEXT DEFAULT 'ACTIVE PREMIUM',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Aktifkan Row Level Security (RLS)
ALTER TABLE public.activations ENABLE ROW LEVEL SECURITY;

-- 3. Buat Kebijakan Akses (Policy) agar Website dapat Membaca & Menambah Data
CREATE POLICY "Allow public select on activations" 
ON public.activations FOR SELECT 
TO public 
USING (true);

CREATE POLICY "Allow public insert on activations" 
ON public.activations FOR INSERT 
TO public 
WITH CHECK (true);

-- 4. Isi Data Awal (Sample Seed Data)
INSERT INTO public.activations (email, code_order, created_at) VALUES
('siti.editpro@hotmail.com', 'AM-993821', NOW() - INTERVAL '5 hours'),
('andrian.motion@gmail.com', 'AM-510492', NOW() - INTERVAL '2 hours'),
('rizky.preset88@yahoo.com', 'AM-772109', NOW() - INTERVAL '11 minutes'),
('budi.editor26@gmail.com', 'AM-849201', NOW() - INTERVAL '3 minutes'),
('zidnifarchanramadhan@gmail.com', 'AM-229984', NOW() - INTERVAL '1 minute')
ON CONFLICT (code_order) DO NOTHING;
